Issue 744 - Current Progress (checking about remove IO[Any,....]) (#805)
* message

* done

* class, classpath, project, settings removed

* removed a lot of unnecessary files

* sbt fmt run

* Most method parameters have been changed to IO, UIO, Task, or TaskR.  Methods organized alphabetically.  Hopefully all other files were deleted.

* .Project file removed

* Scaladoc reformatted. Better return types for specific type aliases

* .gitignore improved

* Finished?

* Conflicts Resolved?

* conflicts turned back

* Zio.scala sorted

* gitignore improved?

* gitignore improved? V2

* .gitignore. removed?

* Issues with missing Classes and Functions

* Ready?

* Clone current file.  Move all ZIO functions into ZIOFunctions.  Moving all functions into object ZIO causes compilation errors.  UIO, IO, Task, TaskR were copied into new clone

* IO got interruptChildren

* Inferred to Any errors fixed

* ZIO.scala organized

* grabbed changes from redone repo

* Compiling after Merge.  'fmt' run.  'Docusaurus' throwing error about 'Cannot run program 'yarn''

* sbt fmt

* Generalized mapAccumM signature #1029 (#1037)

* Generalized mapAccumM signature

* Fixed weird compiler error with explicit type parameters

* Update util-core to 19.6.0 (#1039)

* Update fs2-core to 1.0.5 (#1000)

* Resolve ( #952 - Add links to resources) and fix documentation for effectBlockingCancelable (#978)

* Resolves "Add user provided canceler to effectBlocking" (#966)

 * Add new effectBlockingCancelable method to blocking API
 * Add tests & documentation

* Fix documentatation for effectBlockingCancelable and Add more resources to resources page (#952)

 * Add link to https://freskog.github.io/blog/2019/05/30/explore-zio-stm/
 * Add link to https://github.com/freskog/stm-partitioning
 * Correct documentation for effectBlockingCancelable

* DRY the build (#1019)

* DRY the build

Bring back JDK11 into build matrix

* Disable Dotty builds

* Apparently, apt runs on Ubuntu after bootup

* Implement TracingStatus without bracket to fix a bug found in https://github.com/zio/zio/pull/1041/files#r295777382 (#1047)

* Update sbt-dotty to 0.3.3 (#1042)

* Update sbt-bloop to 1.3.2 (#1043)

* Update sbt-microsites to 0.9.1 (#1044)

* Update sbt-mdoc to 1.2.10 (#1045)

* Return null guard for tracingStatus removed in #1047 (#1051)

* Fix release errors (#1050)

* Fix #987 Disable inlining during non-release builds (#1054)

* Speed up builds (#1055)

* Preserve errors in bracketExit when release dies (#1041)

Similar to how `ensuring` works, we accumulate both errors in
case `use` failed and `release` died.

* Update rxjava to 2.2.10 (#1052)

* Update sbt-mdoc to 1.3.1 (#1053)

* Restore build on tags (#1056)

* Restore build on tags

* Fix syntax

* Remove sneaky \t

* Fix yarn install (#1057)

* Fix yarn install (#1057) (#1058)

* Fix yarn install (#1059)

* Upgrade nodejs (#1060)

* Upgrade nodejs (#1061)

* Hold onto slippery fibers (#1063)

* Hold onto slippery fibers

* fmt

* Fix typo in docs: aa -> a (#1066)

* Fix node and yarn related issues for publishing microsite via circleci (#1068)

* Fix node and yarn related issues for publishing microsite via circleci

* Add nvm

* Add nvm settings

* Update dotty (#1062)

* Cross compile using dotty

* Fix dotty compilation errors

* WIP: disable scala2 macros

* Fix dotty compilation error in tests

* Fix broken links in contributing docs (#1067)

* sbt fmt run

* sbt fmt run

* Pulled in 6-24-19 9:21

* .sbtopts reverted back to the zio's heap size

* Pulled in ignore and parallelErrors

* Test errors fixed in IOSPec and RTSSSpec.  fmt run

* removed un-needed .idea, yarn.lock, node_modules

* onInterrupt cleanup changed to ZIO[R1, Nothing, Any]

* git pull.  All files checked for missing methods.  Explicit type paramater added to ZManageSpec.scala:210 in order to suppress compile error 'Type inferred to be

* Disambiguated IO, Task, TaskR, UIO bracket and bracketExit ScalaDoc links

* Fixed ScalaDoc links V2?

* Fixed ScalaDoc links V3?

* Fixed ScalaDoc links V4?

* Fixed ScalaDoc links V5?

* Fixed ScalaDoc links V6?

* Testing different ScalaDoc links?

* Testing different ScalaDoc links 2?

* Testing different ScalaDoc links 3?

* Testing different ScalaDoc links 4?

* Testing different ScalaDoc links 5?

* Change to @see annotation in companion objects

* Removed ScalaDoc links to bracket and bracketExit.  QueueSubscriber removed from interop-reactiveStreams

* fmt run