Update Scala, dependencies and sbt plugins (#8760)
* Update Scala, dependencies and sbt plugins

* Remove warnings

* Rollback scala-native to v.0.4.x

Because of https://github.com/scalatest/scalatest/pull/2318

* Fix compilation errors

* Fix compilation errors

* scalacheck 1.18.0 is only build for scala-native v.0.5.x

* Clean ci.yml

* Improve `testJvms` CI step to test on 11, 17 and 21

* Remove compilation errors

* Remove compilation errors

* Simplify scala versions declarations

* Unify CI declarations

* Fix import

* Remove compilation errors

* Remove custom sbt script

* Update actions/setup-java

* Update actions/checkout

* Fix CI

* Remove compilation errors

* Try fix CI error:

```
[warn] In the last 10 seconds, 5.18 (52.6%) were spent in GC. [Heap: 0.00GB free of 1.00GB, max 1.00GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.
[warn] In the last 10 seconds, 6.369 (67.4%) were spent in GC. [Heap: 0.00GB free of 1.00GB, max 1.00GB] Consider increasing the JVM heap using `-Xmx` or try a different collector, e.g. `-XX:+UseG1GC`, for better performance.

              total        used        free      shared     buffers       cache   available
Mem:          16768        2589       11296          35         230        2652       13780
Swap:          7516           0        7516
Total:        24284        2589       18812
[error] ## Exception when compiling 16 sources to /home/runner/work/zio/zio/scalafix/input/target/scala-2.13/classes
```

* scalafmt

* Fix CI

* Fix CI

* `Compile / fork := false` is declared twice in the `doc` module

* Debug sbt command

* Put back `JVM_OPTS` envvar

* Rollback `Compile / fork` change

* debug

* debug

* debug

* debug

* debug

* debug

* debug

* Use .jvmopts-ci

* Prefer `SBT_OPTS`

* Debug $SBT_OPTS

* Rollback: Debug $SBT_OPTS

* clean

* Add more debug for future maintainers

* clean

* Remove Java 17 from `testJvms` CI step. It's already tested in other jobs

* Fix compilation

* Fix `build-website` CI step